
class Recarga:
#? Clases para la carga de datos de la tabla de recargas
    def __init__(self, FECHA_PROCESO,AFILIACION,TERMINAL,LOTE,FECHA_TRANSACCION,HORA_TRANSACCION,TARJETA,AUTORIZACION,REFERENCIA,MONTO_CONSUMO,MONTO_TOTAL,IVA_COMISION,MARCA):
        self.FECHA_PROCESO = FECHA_PROCESO
        self.AFILIACION = AFILIACION
        self.TERMINAL = TERMINAL
        self.LOTE = LOTE
        self.FECHA_TRANSACCION = FECHA_TRANSACCION
        self.HORA_TRANSACCION = HORA_TRANSACCION
        self.TARJETA = TARJETA      
        self.AUTORIZACION = AUTORIZACION
        self.REFERENCIA = REFERENCIA
        self.MONTO_CONSUMO = MONTO_CONSUMO
        self.MONTO_IMPUESTO_TURISMO = "0"
        self.MONTO_PROPINA = "0"
        self.MONTO_COMISION = "0"
        self.IVA_COMISION = IVA_COMISION
        self.MONTO_TOTAL = MONTO_TOTAL
        self.MARCA = MARCA

    def __str__(self):
        return f"Recarga(FECHA_PROCESO={self.FECHA_PROCESO}, AFILIACION={self.AFILIACION}, TERMINAL={self.TERMINAL}, LOTE={self.LOTE}, FECHA_TRANSACCION={self.FECHA_TRANSACCION}, HORA_TRANSACCION={self.HORA_TRANSACCION}, TARJETA={self.TARJETA}, AUTORIZACION={self.AUTORIZACION}, REFERENCIA={self.REFERENCIA}, MONTO_CONSUMO={self.MONTO_CONSUMO}, MONTO_IMPUESTO_TURISMO={self.MONTO_IMPUESTO_TURISMO}, MONTO_PROPINA={self.MONTO_PROPINA}, MONTO_COMISION={self.MONTO_COMISION}, IVA_COMISION={self.IVA_COMISION}, MONTO_TOTAL={self.MONTO_TOTAL}, MARCA={self.MARCA})" 
class Validador:
#? Clases para la carga de datos de la tabla de validadores
    def __init__(self,F_PROCESO,AFILIACION,TERMINAL,LOTE,F_TRANSACCION,HORA_TRANSACCION,TARJETA,AUTORIZACION,REFERENCIA,DEBITO,MONTO_TOTAL,MARCA):
        self.F_PROCESO = F_PROCESO
        self.AFILIACION = AFILIACION
        self.TERMINAL = TERMINAL
        self.LOTE = LOTE
        self.F_TRANSACCION = F_TRANSACCION
        self.HORA_TRANSACCION = HORA_TRANSACCION    
        self.TARJETA = TARJETA
        self.AUTORIZACION = AUTORIZACION
        self.REFERENCIA = REFERENCIA
        self.DEBITO = DEBITO
        self.IMPUESTO_TURISMO = "0"
        self.PROPINA = "0"
        self.COMISION = "0"
        self.IVA = "0"
        self.MONTO_TOTAL = MONTO_TOTAL
        self.MARCA = MARCA  
    def __str__(self):
        return f"Validador(F_PROCESO={self.F_PROCESO}, AFILIACION={self.AFILIACION}, TERMINAL={self.TERMINAL}, LOTE={self.LOTE}, F_TRANSACCION={self.F_TRANSACCION}, HORA_TRANSACCION={self.HORA_TRANSACCION}, TARJETA={self.TARJETA}, AUTORIZACION={self.AUTORIZACION}, REFERENCIA={self.REFERENCIA}, DEBITO={self.DEBITO}, IMPUESTO_TURISMO={self.IMPUESTO_TURISMO}, PROPINA={self.PROPINA}, COMISION={self.COMISION}, IVA={self.IVA}, MONTO_TOTAL={self.MONTO_TOTAL}, MARCA={self.MARCA})"